name: flutter_klarna_payment
description: The Flutter Klarna Payment is a Flutter plugin that enables you to integrate Klarna Payments into your Flutter application. 
version: 0.1.3
repository: https://github.com/haoz33/flutter_klarna_payment
platforms:
  android:
  ios:

environment:
  sdk: '>=2.19.1 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
#  plugin_platform_interface: ^2.0.2
  plugin_platform_interface: ^2.1.8
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter_klarna_payment.flutter_klarna_payment
        pluginClass: FlutterKlarnaPaymentPlugin
      ios:
        pluginClass: FlutterKlarnaPaymentPlugin
